=== LoyolaChicagoCode/betterxml.java/bxml/src/main/java/org/betterxml/examples/natural3/particle/nbody.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT NBody (Parameters, InitialConditions)>
<!ELEMENT Parameters (Parameter*)>
<!ELEMENT Parameter EMPTY>
<!ELEMENT Particle EMPTY>
<!ELEMENT InitialConditions (Particle, Particle+)>
<!ATTLIST Parameter name CDATA #REQUIRED
                    value CDATA #REQUIRED>
<!ATTLIST Particle id ID #REQUIRED
                   mass CDATA #REQUIRED
                   unit (g | kg) #REQUIRED
                   x CDATA #REQUIRED
                   y CDATA #REQUIRED
                   z CDATA #REQUIRED
                   velocity CDATA #REQUIRED>

=== LoyolaChicagoCode/betterxml.java/bxml/src/main/java/org/betterxml/examples/natural3/particle/particle.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE NBody SYSTEM "nbody.dtd">
<NBody>
  <Parameters>
     <Parameter name="iterations" value="1000"/>
     <Parameter name="time-limit" value="3:00"/>
  </Parameters>
  <InitialConditions>
     <Particle id="mercury" mass="10" unit="g" 
               x="10" y="100" z="25" velocity="100"/>
     <Particle id="venus" mass="10" unit="g" 
               x="10" y="100" z="25" velocity="100"/>
     <Particle id="earth" mass="100" unit="g"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="mars" mass="100" unit="g"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="jupiter" mass="100" unit="kg"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="saturn" mass="10" unit="kg"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="uranus" mass="100" unit="kg"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="neptune" mass="100" unit="g"
               x="100" y="200" z="30" velocity="20"/>
     <Particle id="pluto" mass="100" unit="g"
               x="100" y="200" z="30" velocity="20"/>
  </InitialConditions>
</NBody>
